### ISSUE TITLE
Add Reaper template for VR audio authoring

### ISSUE THREAD

**Issue by lossius** [ambisonictoolkit/atk-reaper#11]
This template should illustrate the authoring process (encoding, transforms, etc.) with a final conversion from FuMa to ACN/SN3D, so that the resulting B--format file can be used with 360° videos, as supported on Android.

**Comment by lossius** [comment]
@DrWig : Do you have a Reaper template for this more or less ready already? I've seen from your blog and posts on the Facebook VR group lately that you have been working on this.

**Comment by joslloand** [comment]
Hi Trond,

I can do this, actually, and had it in my notes as 'low hanging fruit'.

I was going to take the A-to-B convert and then drop in the new matrices. If you like, I could just forward these to you, and you can drop them in.

Do you have a preference?

**Comment by lossius** [comment]
Moving this issue to the new atk-reaper-examples repository.
