### ISSUE TITLE
Convolution-based encoders and decoders lacks suport for 176.4 kHz

### ISSUE THREAD

**Issue by lossius** [ambisonictoolkit/atk-reaper#13]
This relates to https://github.com/ambisonictoolkit/atk-kernels/issues/3 and affects the following plugins:

Encoders

- Diffuser
- Spreader
- SuperStereo
- UHJ

Decoders

- UHJ

**Comment by joslloand** [comment]
The effected en/decoders should just be:

**Encoders**
- Spread
- UHJ

**Decoders**
- Spherical

**Comment by joslloand** [comment]
Now closed... see note for atk-kernels [issue-3](https://github.com/ambisonictoolkit/atk-kernels/issues/3)
