### ISSUE TITLE
Add loudspeaker polarity indicator to decoder GUIs

### ISSUE THREAD

**Issue by joslloand** [ambisonictoolkit/atk-reaper#21]
@lossius in relation to the GUI enhancement #9, (RMS) levels are now displayed for loudspeaker feeds.

Add an indicator to illustrate the average polarity of channel output feeds. This is "easily" calculated. E.g.:

`polarityLF = TimeAverage(LF * W)`

By monitoring the polarity of `polarityLF` we can determine whether the average signal presented at `LF` is "in phase" or "out of phase" with W. This is a _very useful_ indicator illustrating decoder performance and soundfield quality.

**Comment by joslloand** [comment]
More details... there are actually three states of interest:

1. `polarity > 0` means "in phase"
2. `polarity = 0` means "in quadrature"
3. `polarity < 0` means "out of phase"

I'm thinking these states could be represented by a color or shading change of the current metering.

**Comment by lossius** [comment]
Moving to wiki, closing this issue
