### ISSUE TITLE
Add useful track templates to Reaper

### ISSUE THREAD

**Issue by mtmccrea** [ambisonictoolkit/atk-reaper#23]
This could be as simple as including the Reaper "theme" Mike already made, which is basically 2 variations on the Mixer track interface to make meters larger and remove controls which are extraneous when working with ambisonics. Shown and described [here](https://dxarts.washington.edu/wiki/ambisonic-mixing-reaper#track-layouts). 

More elaborate layouts could be made... Note the layouts in the link above are only for the Mixer panel layouts (as opposed to Track panel layouts).  Similar modifications could be done on the Track panel tracks, if someone wants to take on the black art of [WALTER](http://www.reaper.fm/sdk/walter/walter.php) hacking.

**Comment by lossius** [comment]
I finally got the time to check out this theme, and it's nice. I have one minor comment for you @mtmccrea : Would it be possible to keep the Track Envelopes/Automation button in the Mixer panel? I sometime finds that useful.

**Comment by mtmccrea** [comment]
@lossius - I've updated the reaper theme file to include the envelope button in the mixer tracks. The updated file is [here](https://nas.dxarts.washington.edu/share.cgi?ssid=0ad7boc).

The link on the DXARTS wiki ambisonic/Reaper tutorial is also pointing to this new theme file.

**Comment by lossius** [comment]
Super, thank you! I have the theme here now, and will see how I can integrate it into the installer.

**Comment by mtmccrea** [comment]
Sure thing! It wouldn't hurt to do a quick test to confirm it's what you're looking for... Let me know if there are any hiccups.

**Comment by lossius** [comment]
Addressed in 	3bffec9
