### ISSUE TITLE
Provide Reaper project examples

### ISSUE THREAD

**Issue by lossius** [ambisonictoolkit/atk-reaper#25]
When developing the example projects, it will be useful to examine the sc3 examples, and ensure that important aspects are covered.

The best would be to collect all example projects in a shared folder with media files residing in a media subfolder. This media subfolder could then be a git submodule of the atk-sounds, so that we don't have to maintain the example sound files several times over.

The examples would require the disk space of atk-sounds, so we might want to consider whether we want to include it in atk-reaper itself, or rather set it up as a separate install and download. But the most user-friendly experience once downloaded may be to have it all in the same place.

**Comment by joslloand** [comment]
Would there be an easy way for the Reaper projects to have a symbolic link to the atk-sounds folder? E.g., to: `~/Application Support/ATK/sounds`

The thought is, it would be great if the user just needs to install the various assets in their "official" target directories, and then the example Reaper sessions would just look to those locations.

**Comment by lossius** [comment]
> Would there be an easy way for the Reaper projects to have a symbolic link to the atk-sounds folder?

Yes, but I doubt that we want to do it. The problem is that Reaper creates *.reapeaks files for each sound file that it loads in order to be able to draw sound waves faster. These peak files by default end up in the same folder as the sound file itself, and introduce a lot of noise in the folder structure.

If there was a way of setting where peak files go on a per project basis, it would be less of a problem, but unfortunately I don't think this can be controlled in any other way than as a global Reaper preference that affects all projects.

On my laptop I have set Reaper to store peak files in a peak/ subfolder. That helps, but regardless I would imagine that the reapeak files would be an annoiance when using ATK with SuperCollider.

I would guess that most users that are concerned about disk space will download Reaper example projects and put them on an external disk so that it is not filling up the main hard drive. If so I don't think it matters to much that the sound files gets downloaded twice, once for sc3 and once for Reaper.

**Comment by joslloand** [comment]
> The problem is that Reaper creates *.reapeaks files for each sound file that it loads in order to be able to draw sound waves faster. These peak files by default end up in the same folder as the sound file itself, and introduce a lot of noise in the folder structure.

&

> I would imagine that the reapeak files would be an annoiance when using ATK with SuperCollider.

Ok, agreed. We don't want to make a big mess. While most users don't actually view the ATK assets folders, keeping clutter down is a good idea.

> If so I don't think it matters to much that the sound files gets downloaded twice, once for sc3 and once for Reaper.

Ok, I can see the rationale here....

What about, packaging the Reaper projects as described, but instead of including the soundfiles themselves, the Reaper folder contains links to `ATK/sounds/[file name]`?

That is, instead of having the Reaper project link to `ATK/sounds`, the individual files are linked. Would something like that work?

The thought is that then Reaper would draw all the peaks in the project file rather than `ATK/sounds`?

**Comment by lossius** [comment]
I have set up a new project for this:

https://github.com/ambisonictoolkit/atk-reaper-examples

I din

**Comment by lossius** [comment]
I don't think that it is a good idea to add symbolic links and "reuse" atk-sound files residing somewhere else. Reaper-users might not have downloaded and installed atk-sounds at all, and I am afraid that we

**Comment by lossius** [comment]
Closing this issue, as further requests for examples should be added as issues in the new repository.

**Comment by joslloand** [comment]
@lossius thanks for setting up the [new repo](https://github.com/ambisonictoolkit/atk-reaper-examples)!
