### ISSUE TITLE
Reconsider quad decoder channel configuration

### ISSUE THREAD

**Issue by lossius** [ambisonictoolkit/atk-reaper#26]
Currently it outputs to ch 1-2 and 5-6 using the same channel ordering that is common in many standard plugins and panners for 5.1 and 7.1 surround, with the following channel ordering:

1: Left 
2. Right
3. Center
4. LFE
5. Sur Left
6. Sur Right
7. Sur Back Left
8. Sur Back Right

Is this the best design, or would it be better to just have four channels out:

1: Left 
2. Right
3. Sur Left
4. Sur Right

A change would break backwards compatibility.

If you have opinions on this, please let us know here.

**Comment by joslloand** [comment]
I'm feeling four channels out:

1: Left 
2. Right
3. Sur Left
4. Sur Right

is the way to go.

Users making pieces for quad would expect to be able to easily write out a four channel file without remapping the outputs.

Similarly, for my quad system at home, the above arrangement describes my arrangement.
