### ISSUE TITLE
Missing README & License for atk-reaper install on OSX

### ISSUE THREAD

**Issue by joslloand** [ambisonictoolkit/atk-reaper#28]
Running the installer for atk-reaper doesn't appear to include writing the licensing to into the Reaper Effects directory on OSX.

I'd presume the installer would write:

`~/Application Support/REAPER/Effects/ATK/README.md`
`~/Application Support/REAPER/Effects/ATK/License.md`

There could be an argument that the user has already read the license and readme in running the installer, but I'd assume these files would be written for further reference / documentation.

**Comment by lossius** [comment]
I don't think it is a good idea to copy README and LICENSE to the `~/Application Support/REAPER/Effects/` folder. These two files will then show up in the window within Reaper where you select what plugin to use. I will personally experience this as undesired noise. It is better to ensure that we have license info properly provided in the header of each file.

**Comment by joslloand** [comment]
@lossius, ok, that'll work if it shows up in the code. I was just browsing the resulting files written by the installation, and didn't see these where I'd expected.

The trick, will be to be sure that the information found in `README.md` & `License.md` are correctly echoed in the header of each file.
