### ISSUE TITLE
Improve GUI for mono decoder

### ISSUE THREAD

**Issue by lossius** [ambisonictoolkit/atk-reaper#41]

**Comment by joslloand** [comment]
@lossius, I'm presuming you may also be thinking of adding an illustration of the resulting polar pattern?

**Comment by lossius** [comment]
Yes, that has been the idea, but I don't know where I might find code that I can use for drawing it?

**Comment by joslloand** [comment]
@lossius, something else that might also be useful is to add keywords for common mic patterns:

pattern | virtual microphone
-------- | ----------------------
0.0 | Omni
0.5 | Cardioid
(3-sqrt(3))/2 | Super-cardioid
0.75 | Hyper-cardioid
1.0 | Bi-directional

These values are already included in the current docs for atk-sc3 mono decoder.

There is also a relationship to decoder **k**, given a uniform periphonic (3D) distribution of loudspeakers, e.g. a Platonic solid:

keyword | decoding | virtual microphone | pattern
--------- | ----------- | ---------------------- | --------
`'velocity'` | strict soundfield | Hyper-cardioid | 0.75
`'energy'` | energy optimised | Super-cardioid | (3-sqrt(3))/2
`'controlled'` | controlled opposites | Cardioid | 0.5

**Comment by joslloand** [comment]
Also... doing a polar plot of the resulting pattern is relatively trivial. It just depends on how fancy we want to get. If we just want to illustrate the resulting polar pattern, in the form found here:

![2D mic patterns](http://www.telefunken-elektroakustik.com/images/gfx/mic_patterns.gif)

I.e., without illustrating orientation, it is just a simple matter of using the pattern value to calculate the vector length, given a test angle input:

`r = (1-pattern) + (pattern * cos(theta))`

Thinking in terms of Ambisonics, the first part is **W** (scaled to unity, i.e., `sqrt(2) *  W`) and the second part is **X**. The `pattern` value is controls the weight between the two.

Going 3D takes a bit more effort, but is along the same lines:

![3D mic patterns](http://www.istockphoto.com/generic_image_view/119805/119805)

Some other kinds of plots include the VVMic 2D display:

![VVMic](https://www.vvaudio.com/sites/vvaudio7/files/VFT_Big.preview.png)

And, VVDecode includes a 3D "bubble" display:

![VVDecode](https://www.vvaudio.com/sites/vvaudio7/files/VVDecode_ORTF.png)

--
These aim-able displays take some more effort, but are simply based on calculating a vector length based on the `pattern` value.

So... I expect the question is which of these kinds of displays are we wanting to implement. The easiest, of course, is just to plot the 2D polar pattern, aimed at 0 deg.

--
And... another useful tool to look at is the Sengpiel Audio [stereo microphone visualiser](http://www.sengpielaudio.com/Visualization-Blumlein-E.htm).

**Comment by lossius** [comment]
Thanks, @joslloand 

I'll go with the formula that you write in the first of your comments. I believe it is straight-forward to combine this with also displaying the angle that the mic is pointing towards, I'll be able to do that.

And I can see that it might be worthwhile considering this for the stereo decoder as well.

Reaper have no support for 3D animation, so the more fancy ones are out of reach for the time being.

Re keywords: I can imagine two ways of doing this:

1. As a set of presets for the plugin
2. Using a "display" only parameter with a list of words that can be displayed, and that jumps to the word that is closest to the current. Alternatively the "nearest" mic pattern can be displayed in the GUI itself.

I hadn't realised the link between k and mic pattern. Thanks for this, I'm always learning something new.
