### ISSUE TITLE
Binaural Decoder doesn't work

### ISSUE THREAD

**Issue by rodrigodzf** [ambisonictoolkit/atk-reaper#44]
Hi,

I downloaded the reaper plugin, however, the binaural decoder doesn't seem to work.

How to replicate:
using Reaper x86_64 v5.22 - July 14, 2016.
using ATK_for_Reaper_Mac_1.0.b7

Fresh install both and use fx ATK FOA Decode Binaural. Sound comes in but nothing comes out. (I had to copy the effects folder ~/Library/Application Support/REAPER/Effects to ~/Applications/Effects because Reaper doesn't recognize the plugin in the first folder somehow)

The issue might be in the path of the IRs. I tried to set a different path to no avail. Any suggestions?

Thanks!

**Comment by joslloand** [comment]
@rodrigodzf do any of the kernel decoders work, or is it just the binaural decoder?

Can you try the UHJ decoder?

Also, were things working for you with your previous instal?

**Comment by rodrigodzf** [comment]
Thank you for your answer @joslloand. I tried the UHJ Decoder and it also fails, none of the other ATK plugins fail. This is the first time I installed the ATK plugin. Also, my project settings are 44.1Khz sample rate/512 buffer size.

**Comment by mtmccrea** [comment]
@rodrigodzf it sounds like you may not have the kernels in the right place. Can you confirm that you have a **kernels** folder installed in `~/Library/Application Support/ATK`.  You'll also want to check that your project settings match your hardware sample rate (which you'll find in **Preferences>Sound** or the **Audio MIDI Setup** application).

> (I had to copy the effects folder ~/Library/Application Support/REAPER/Effects to ~/Applications/Effects because Reaper doesn't recognize the plugin in the first folder somehow)

This also seems odd...perhaps a configuration setting in REAPER? Did any plugins work (not just ATK) when you had the Effects folder in the proper place (`~/Library/Application Support/REAPER/Effects`)?

**Comment by rodrigodzf** [comment]
I reinstalled Reaper again. On the first run after install, Reaper creates the ~/Applications/Effects and it seems that it copies the contents of ~/Library/Application Support/REAPER/Effects to that folder. All the default JS plugins work (their location points to ~/Applications/Effects/* in the editor though). I have ~/Library/Application Support/ATK and the symbolic link ~/Library/Application Support/REAPER/Data/ATK pointing to it.
The project uses the default hardware sample rate.

**Comment by lossius** [comment]
Hi @rodrigodzf , I'm just back from vacation.

The first issue that need to get solved here is that the plugins need to be installed in the proper location. With plugins installed to `~/Applications/Effects` I'm pretty sure that they are unable to find the kernels.

1) Can you please start out by deleting the following folders (when Reaper is not running)

    ~/Applications/Effects
    ~/Library/Application Support/REAPER/
    ~/Library/Application Support/ATK/

2) Next, please start. This should recreate a default `~/Library/Application Support/REAPER/` folder. 

3) Next, please try loading any JS plugin and check if that works. When adding an effect to a track and selecting JS from the list in the left window, several plugins should be listed:

<img width="883" alt="screen shot 2016-07-24 at 14 40 16" src="https://cloud.githubusercontent.com/assets/38478/17083840/ab008296-51ac-11e6-98d7-dde914e9c330.png">

You might not necessarily have the same (or as many) plugins as I do, but there should be a number of plugins showing up.

4) Next, try loading the  `Convolution Amp/Cab Modeler` plugin. This is a standard plugin that comes with Reaper and use convolution. Test it out and see if it works, and if the processed sound of whatever you pass through it changes as you choose different amp models. If this works, we know that this model is able to find the impulse response files needed. That would be a good first step.

5) Now, quit Reaper and please download and run the ATK for Reaper installer. Do not move any files to other locations, leave them in the default location that they are installed into.

6) Set up a new project and test some of the ATK plugisn that do not depend on kernels, such as:

* ATK FOA Encode Planewave
* ATK FOA Transform Direct
* ATK FOA Transform FocusPressPushZoom
* ATK FOA Decode Stereo

Are you able to load these, and do they work for you?

7) Making sure that your project is at 44.1 kHz, try some of the kernel-based plugins such as:

* ATK FOA Encode Spreader
* ATK FOA Decode Binaural
* ATK FOA Decode UHJ

Do these work for you now?

If you still have problems, please report back. I have the plugisn working here with the same version of Reaper as you, and OSX 10.11.6.

I hope to upload a new version of ATK for Reaper in the next few hours, I just need to do some testing first.

Thanks!

**Comment by lossius** [comment]
@rodrigodzf : I've upladed a new beta version now (beta 9). Please use that installer for further testing. Thanks!

**Comment by rodrigodzf** [comment]
Hi @lossius, Thank you for your answer, the new version seems to work well! The bug might have been related to me not deleting `~/Library/Application Support/REAPER/` in the first place, because the `~/Applications/Effects` folder is not created on start anymore.

Thanks again!
