### ISSUE TITLE
atk-reaper and atk-sc3 decoder/encoder channel ordering compatibility?

### ISSUE THREAD

**Issue by joslloand** [ambisonictoolkit/atk-reaper#50]
@lossius 

Do we want to add a drop-down menu for encoders / decoders (e.g., 5_0) to accommodate traditional Ambisonic channel ordering?

Why this would be "easy"... The required matrices will be authored and accessible from the matrices folder. I.e., there will be a set of matrices for atk-sc3 and another set for atk-reaper. The atk-reaper versions will be loadable from atk-sc3.

This question / suggestion is for the possibility of atk-reaper plugins being able to select which matrices to load via an option for the plugin.

**Comment by lossius** [comment]
It is better to solve this via the pin connector matrix that is provided for all plugins in Reaper. Now that we have good indications of channel order in the GUIs of all encoders and decoders, I believe we are fine.

Closing this issue.

**Comment by joslloand** [comment]
Makes sense, now the labels are included.
