### ISSUE TITLE
azimuth parameters + automation or parameter modulation = broken

### ISSUE THREAD

**Issue by lossius** [ambisonictoolkit/atk-reaper#57]
Automation produce audible glitches when passing the -180/+180 threshold.
Parameter modulation doesn't work at all.

This issue shows up in parameters that their range inverted (so higher parameter value to the left on sliders), which is only the case for azimuth angle in a number of plugins.

Both issues are believed to be issues with Reaper rather than the ATK plugins. The issue has been reported to Reaper developers.

**Comment by joslloand** [comment]
This is probably a result of the parameter smoothing....

One possibility could be to do some internal wrapping of the values?

**Comment by lossius** [comment]
It used to work fine and it still works fine when controlled from the GUI, so I'm pretty sure this is a problem with Reaper, not ATK plugs.

**Comment by joslloand** [comment]
Ah.. sounds like a Reaper problem then!

**Comment by lossius** [comment]
This issue comes up when using interpolations between automation points in Reaper. the solution is to not do so.
