### ISSUE TITLE
Differences in repo and ATK site.

### ISSUE THREAD

**Issue by Atavic** [ambisonictoolkit/atk-reaper#61]
What's the difference between the releases provided here and the releases in [ Ambisonic Toolkit website](http://www.ambisonictoolkit.net/)? I ask this because I can't get the whole file from dropbox (it drops before getting the whole file).

**Comment by lossius** [comment]
The versions here are auto-generated when I tag the repository. The releases from the website are the ones to look for. Plkease try using a different browser, or clear the cache. Hopefully that will help.
