### ISSUE TITLE
drawbackgroundimage() causing issues

### ISSUE THREAD

**Issue by rclough** [ambisonictoolkit/atk-reaper#62]
Hello,

i recently upgraded from b6 to b10,and the GUIs fail to draw because reaper JS is complaining with the error:

``` 
'drawBackgroundImage' needs 6 params: 'drawBackgroundImage( <!> )'
```

I couldn't find any documentation online about this function, so I tried commenting out this part of the code and it seems to make the code work, but I imagine I'm missing something?

**Comment by rclough** [comment]
perusing the code some more, I found the included library that contains the function, it seems indeed there is only one definition, 

``` javascript
function drawBackgroundImage() local(i, lDeltaX, lDeltaY)
```

I'm not super familiar with reaper JS syntax, but this seems to me like it takes no argumentsso I'm not sure why reaper would complain that it expects 6 args? later in the code there is this commented out bit that seems to use 6 args though:

```
  //drawBackgroundImage(661, 1, left, top, stripWidth, stripTotalHeight);
```

at this point I'm sort of above my head with jsfx (never really touched it before this moment)....maybe reaper cached an old version of the library files? I checked in my b6 version and it appears that older version took 6 args....

reaper version: 5.27/x64 rev fe8558

**Comment by rclough** [comment]
Figured it out!

It seems at some point, the library went from using `.../Effects/ATK/FOA/lib/..."  to ".../Effects/ATK/Libraries". When I updated to b10, I had both folders. Once I deleted the old "lib" folder, everything went back to working again.

Quickly looking on the changelog, I didnt see any note about this, so in case anyone else encounters the issue, I hope this helps

**Comment by lossius** [comment]
Hi, I discovered in the aftermath of the release, and have fixed this for future releases, so that older installs are automatically deleted on mac when doing a new install.

Cheers!
