### ISSUE TITLE
HOA: Consider variable Order argument for HOA plugins

### ISSUE THREAD

**Issue by joslloand** [ambisonictoolkit/atk-reaper#63]
Suggested by Enda Bates:

> I would love it if the order of the encoder/decoder/transform can be set within the plugin, rather than having separate plugins for FOA, 3rd order, 5th order, or whatever. 
> 
> The reason I ask is that it's happened to me a few times where I needed to change a piece created in one order, to a different order, and if you have lots of automation of azimuth, elevation, etc, it's a real pain to have to copy all of that automation across to a new plugin (I had a concert piece in 3rd order, which was then played on a rig that could up to 5th. Also I've done a few VR projects that started in FOA, but then the possibility came up to go to 3rd order). If you could just set the order in the plugin, then all the automation could stay the same, and you'd just need to add the extra channels and tweak the routing (which you would have to do anyway, and is pretty trivial in Reaper).

**Comment by lossius** [comment]
This is a very good point. The IEM plugins are good examples of this kind of design.

 I am moving this to a wiki page, as this is more a design concern than a simple and singular task to do, and close this issue.
