### ISSUE TITLE
HRTF Binaural

### ISSUE THREAD

**Issue by nancynelma** [ambisonictoolkit/atk-reaper#68]

**Comment by joslloand** [comment]
Have a look at the [README](https://github.com/ambisonictoolkit/atk-kernels#decoders) for the decoder kernels. Here there is a discussion of the HRTF decoders for the ATK.

The [CIPIC HRTF database](http://interface.cipic.ucdavis.edu/sound/hrtf.html) provides two KEMAR dummy measurements. subjectID = 21 is the large pinnae dummy and subjectID = 165 is the small pinnae dummy.

You may like to review the [discussion here](http://doc.sccode.org/Classes/FoaDecoderKernel.html#*newCIPIC).

Hope this helps.

**Comment by lossius** [comment]
Hi, @nancynelma - addint to @joslloand 's reply above, most of the CIPIC decoders display a photo of the head used for the measurement. This might help you find an ear that resembles your own. The spherical HRTFs are size-dependent, starting with the smallest and progressing towards the largest (9). Try them out taking your own head size into account and listen to judge for yourself which one works the best for you.

Unfortunately no photos are available for the IRCAM Listen HRTFs.
