### ISSUE TITLE
Suggestion for the Tutorial Videos/Website

### ISSUE THREAD

**Issue by ghost** [ambisonictoolkit/atk-reaper#69]
Hey,

I recently found the Reaper ATK and really love it.
In the tutorial videos you are using the Harpex plugin for visualisation. Now this plugin is very expensive and by accident I stumbled over the Waves "Nx – Virtual Mix Room over Headphones" Plugin:
https://www.waves.com/plugins/nx
This tool also supports an first order ambisonic visualisation mode:
![nx-ambi](https://user-images.githubusercontent.com/4435871/34416753-3ed45f9a-ebf5-11e7-943d-62ae5b725625.jpg)
The 3D view can be freely rotated and the plugin also does great Binaural decoding.
It even features realtime headtracking via a webcam or special bluetooth device.
It normally costs about 99$ but in sales it can be had for below 50$.
This may be a great alternative for people just starting with ambisonics and not willing or able to shell out for the Harpex plugin.
May be helpful to mention it as an alternative on the website.

Cheers and thanks again,

Tom

**Comment by lossius** [comment]
I would rather recommend the Audio Ease 360 plugins as they also support higher order. Thanks for the suggestion though. Closing this issue.
