### ISSUE TITLE
various problems!

### ISSUE THREAD

**Issue by cdbzb** [ambisonictoolkit/atk-reaper#71]
( this is a duplicate - I left this at the end on another thread in error )

Hi there - I am running Mac Sierra and the most recent REAPER pre-release.

the binaural decoder does not pass audio
also the mono diffusor encoder does not pass audio

the installer fails (I was able to get some a partial instqallation by inspecting the installer contents and installing the package in the Contents folder. In this case though the files were placed in the system rather than user library.

At this point perhaps it would be more useful to simply provide the files and full install instructions? Also you might consider using the ReaPack package manager (like SuperCollider's Quarks). I think this is fabulous package but I wish I could get it all working! thanks in advance

**Comment by lossius** [comment]
Hi @cdbzb , your probblem has to do with the impulse respponses (kernal files) not being found by the plugins that depend on convolutions. My guess is that also no images show up nin the GUI of the binaural decoder. If you download the window installer instead and follow those instructions, you should be fine.

**Comment by cdbzb** [comment]
yes that solved it. thank you!
