### ISSUE TITLE
Small bug in ATK FOA Decoder Psycoshelf

### ISSUE THREAD

**Issue by gsenna** [ambisonictoolkit/atk-reaper#75]
Hi,

Should line 94 of the ATK FOA Decoder Psycoshelf read as

`wc = tan($PI * mFreq * inverseSamplesblock);`

instead of

`wc = tan(pi * mFreq * inverseSamplesblock);`

?

Thanks!

**Comment by joslloand** [comment]
@lossius, the line in question: https://github.com/ambisonictoolkit/atk-reaper/blob/master/plugins/FOA/Decode/PsychoShelf#L94

**Comment by joslloand** [comment]
compare with: https://github.com/ambisonictoolkit/atk-reaper/blob/master/plugins/FOA/Transform/NearfieldProximity#L126

**Comment by gsenna** [comment]
Hi,

Thanks for the quick reply. Another issue seems to be that the filter becomes unstable depending on the `samplesblock` used. 128 works, but with values like 256 and 512 the amplitude blows up.

**Comment by lossius** [comment]
I set up a new issue #78 to address the instability, and close this one.
