### ISSUE TITLE
Add loudspeaker polarity indicator to decoder GUIs

### ISSUE THREAD

**Issue by lossius** [ambisonictoolkit/atk-reaper#86]
@lossius in relation to the GUI enhancement #9, (RMS) levels are now displayed for loudspeaker feeds.

Add an indicator to illustrate the average polarity of channel output feeds. This is "easily" calculated. E.g.:

`polarityLF = TimeAverage(LF * W)`

By monitoring the polarity of `polarityLF` we can determine whether the average signal presented at `LF` is "in phase" or "out of phase" with W. This is a _very useful_ indicator illustrating decoder performance and sound-field quality.

More details... there are actually three states of interest:

`polarity > 0` means "in phase"
`polarity = 0` means "in quadrature"
`polarity < 0` means "out of phase"

I'm thinking these states could be represented by a colour or shading change of the current metering.

**Comment by lossius** [comment]
<img width="622" alt="Screenshot 2022-02-02 at 22 42 52" src="https://user-images.githubusercontent.com/38478/152242220-3e71bc20-5647-414c-a05a-990fbe095db1.png">

@joslloand I now have a working prototype of this for the Quad decoder. Before going further it would be useful to understand better how you interpret this information. Is a reversed polarity something that is generally not desired (considered an error)? Or is this more "neutral" information, ao that there might be a difference in colour or brightness, but not necessarily in a way that signals an error (red) or warning (orange, yellow)?

From initial tests with a number of encoders and transforms from ATK, it seems difficult to end up with reversed polarity unless I start tinkering with the encoded signal itself in irregular ways (reducing the gain of W).

**Comment by joslloand** [comment]
@lossius No, inverse polarity is _an important part_ of how things actually work. With basic (aka velocity) decoding, the opposite loudspeakers have inverse phase. This is the "pulling" opposed to the "pushing" of the speakers in the source direction, and increases the length of the velocity vector to 1.0, matching that of a real source.

For energy decode, the inverse "tail" is reduced, concentrating energy in the direction of the source, but reducing the length of the velocity vector.

For controlled opposites decode (aka cardioid) the tail is reduced to null. There is no inverse element, but the energy is spread. The magnitude of the velocity vector is further reduced, as is the energy vector.

So, yes, the most localized results (in or near the sweet spot) have inverse signals opposite the main source. Essentially we're recreating the target beam pattern with the loudspeakers.

Have a look at the first figure, [here](https://www.researchgate.net/publication/267852835_The_Composition_and_Performance_of_Spatial_Music/figures?lo=1).

Make sense?

**Comment by joslloand** [comment]
Whoops, the figure of interest is: Fig. 4.8 Directivity patterns of various ambisonic decoding schemes

**Comment by lossius** [comment]
@joslloand 

Thanks for your feedback.

I'm closing this issue now as the feature is implemented, but two issues occur to me to consider further:

1) We might have to do a proper quality check on all decoders. I see some inconsistencies in the 5_0 decoder.
2) None of the decoders apart from the (regular) stereo have any options to adjust mic patterns. If this is a feature that ought to be available for all plugins, we should consider how to implement that.

please feel free to check how the plugins currently work on the v12-graphics branch, ad if you notice issues, create new ones. It might be that one of the next milestones should deal with the quality assertion of decoders.

**Comment by joslloand** [comment]
Hello @lossius, yes to both of these.

There are some inconsistencies and quality issues. I'd also say there are short term and long term things to consider. @mtmccrea has expressed an interest in reviewing these... which should probably go into another thread / discussion.

> 2. None of the decoders apart from the (regular) stereo have any options to adjust mic patterns. If this is a feature that ought to be available for all plugins, we should consider how to implement that.

The answer to this is, _mic patterns_ should not be a "direct" option. Instead, the classic Ambisonic _beam patterns_ should be offered. There are three to choose from that are implemented in the SC3 version:

1. _basic_, aka velocity
2. _energy_ optimized
3. _controlled_ opposites, aka cardioid

Looking at [generateDecodePantoMatrix](https://github.com/ambisonictoolkit/atk-reaper/blob/master/plugins/libraries/atk/atkMatrixLibrary.jsfx-inc#L484-L517), it appears that controlled opposite beams are being generated... but I haven't had a deep look... so I could be wrong here!

In practice, we _should_ seek to unify the beam weighting as is managed in the SC3 version.

For comparrison here's the [HOA projection decoder matrix](https://github.com/ambisonictoolkit/atk-sc3/blob/master/Classes/HoaMatrix.sc#L1264-L1344), aka Simple Ambisonic Decoding (SAD). (Some of the complication here is that we need to reduce order if we don't have enough loudspeakers.)

Here's the [FOA panto projection decoder matrix](https://github.com/ambisonictoolkit/atk-sc3/blob/master/Classes/FoaMatrix.sc#L693-L727). This is much more on the lines of how the current `generateDecodePantoMatrix` is set up. The `k` argument is the beam weight the user can choose. Here's the [2D weights](https://github.com/ambisonictoolkit/atk-sc3/blob/master/Classes/FoaMatrix.sc#L582-L599) which could be implemented in `generateDecodePantoMatrix`. For single band decoding, we'd just use the [first three](https://github.com/ambisonictoolkit/atk-sc3/blob/master/Classes/FoaMatrix.sc#L588-L590) weights.

----

**NOTE:** the HOA version implements the "modern" approach and also offers choices of gain normalization, aka _matching gain_. (Choices: _beam_, _amp_ (aka _pressure_), _rms_, _energy_.) I'd have to review things, but I seem to recall that classic FOA usually chooses _amp_ (aka _pressure_) for single band decoding and _rms_ for dual band (aka shelf filtering) decoding, and I think that this is what is implemented on the JSFX side.

Anyway... it would be great if we could be "modern" on the DAW plugin side of things.
