### ISSUE TITLE
Help needed for install on Mac OS

### ISSUE THREAD

**Issue by leo-nerd** [ambisonictoolkit/atk-reaper#95]
Hello. The link on ambisonicstoolkit.net to download the package for Mac OS appears to lead to a broken Dropbox page. I cannot work out how to build the .dmg from the files in the "installer" folder on this repo as an alternative. Thanks!

**Comment by lossius** [comment]
@leo-nerd : I just tested, and I see that in Dropbox you get a "Couldn’t preview this file" as disk images can't be previewed by Dropbox. Still, there is a download button, and it is confirmed to work. Please try again, and if you don't figure it out, you can always download the Windows version instead and install it manually. That works just as well on macOS. there is no difference (or platform-specific content) in the macOS installer, it is just a convenience to make for an easier install.

Closing this issue.
