### ISSUE TITLE
Broken MacOS download link

### ISSUE THREAD

**Issue by joslloand** [ambisonictoolkit/atk-reaper#97]
Confirmed!

For the Mac link I get this: https://bitly.com/a/blocked?hash=3BVVJDX&url=https%3A%2F%2Fwww.dropbox.com%2Fs%2Fh68lrksnr5eaukh%2FATK_for_Reaper_Mac_1.0.b11.dmg%3Fdl%3D0

However, for the Windows link, it goes through: https://www.dropbox.com/s/85oimjlepz6kym4/ATK_for_Reaper_Win_1.0.b11.zip?dl=0

**Comment by joslloand** [comment]
> Trond posted the full link on the FB group.

**Comment by joslloand** [comment]
**Update**

Here's the direct macOS link: https://www.dropbox.com/s/h68lrksnr5eaukh/ATK_for_Reaper_Mac_1.0.b11.dmg

**Comment by lossius** [comment]
I assume that the reason why we get the Bitly problem is that the macOS installer is not codesigned.

**Comment by joslloand** [comment]
> I assume that the reason why we get the Bitly problem is that the macOS installer is not codesigned.

Hmm.... could be.

It is also worth noting that the various **Previous Versions** download links on [Download ATK for Reaper](https://www.ambisonictoolkit.net/download/reaper/) are also now broken, too.

**Comment by joslloand** [comment]
https://github.com/ambisonictoolkit/ambisonictoolkit.github.io/commit/d34432da949d8a1911fc17148d33a490cff024c7#commitcomment-74412588
